
import type { Listing, RoommateProfile, Advertisement, Coupon, StaffMember } from './types';

export const dummyAdvertisements: Advertisement[] = [
    {
        id: 'ad001',
        title: 'Grand Opening Offer!',
        description: 'Get 50% off on all listing plans for a limited time. Use code: GRAND50',
        imageUrl: 'https://placehold.co/600x400',
        isActive: true,
    },
    {
        id: 'ad002',
        title: 'Unlock Unlimited Connections',
        description: 'Subscribe to our unlimited plan and find your perfect roommate today.',
        imageUrl: 'https://placehold.co/600x400',
        isActive: false,
    }
];

export const dummyCoupons: Coupon[] = [
    { id: 'coupon001', code: 'STAY20', discountPercentage: 20, isActive: true },
    { id: 'coupon002', code: 'NEWUSER', discountPercentage: 15, isActive: true },
    { id: 'coupon003', code: 'EXPIRED', discountPercentage: 50, isActive: false },
];

export const dummyStaff: StaffMember[] = [
    { id: 'S001', name: 'Ravi Kumar', userId: 'StaffRavi', password: 'password1' },
    { id: 'S002', name: 'Sunita Sharma', userId: 'StaffSunita', password: 'password2' }
];

export const dummyProperties: Listing[] = [
    {
        id: 'premium-pg-cbd',
        propertyType: 'PG',
        title: 'Premium PG for Professionals',
        rent: 18000,
        area: 150,
        city: 'Navi Mumbai',
        locality: 'CBD Belapur',
        state: 'Maharashtra',
        completeAddress: '101, Elite Residency, Sector 11, CBD Belapur, Navi Mumbai, Maharashtra 400614',
        partialAddress: 'Sector 11, CBD Belapur, Navi Mumbai',
        ownerName: 'Rohan Mehta',
        contactPhonePrimary: '+919911223344',
        contactEmail: 'rohan.m@example.com',
        description: 'A premium PG accommodation offering single rooms with all modern amenities. Ideal for working professionals seeking comfort and convenience in CBD Belapur.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Meals', 'Laundry', 'Housekeeping', 'Security'],
        size: 'Single Room',
        images: [
            'https://placehold.co/600x400',
        ],
        views: 125,
        ownerId: 'dummyOwner1',
        brokerStatus: 'Without Broker',
        vendorNumber: 'VN-582193',
        beds: [
            { id: 'bed1', status: 'occupied' },
            { id: 'bed2', status: 'vacant' },
            { id: 'bed3', status: 'vacant' },
            { id: 'bed4', status: 'occupied' },
        ],
        lastAvailabilityCheck: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
        status: 'approved',
        submittedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S001',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
        nocUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'luxury-2bhk-vashi',
        propertyType: 'Rental',
        title: 'Luxury 2BHK Apartment',
        rent: 45000,
        area: 1200,
        city: 'Navi Mumbai',
        locality: 'Vashi',
        state: 'Maharashtra',
        completeAddress: '205, Ocean Breeze, Sector 17, Vashi, Navi Mumbai, Maharashtra 400703',
        partialAddress: 'Sector 17, Vashi, Navi Mumbai',
        ownerName: 'Smita Patel',
        contactPhonePrimary: '+918877665544',
        contactPhoneSecondary: '+919876543210',
        contactEmail: 'smita.p@example.com',
        description: 'Elegantly designed 2BHK apartment in the heart of Vashi. Features spacious rooms, modern kitchen, and access to all city conveniences.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Parking', 'Gym', 'Elevator', 'Security'],
        size: '2 BHK',
        images: [
            'https://placehold.co/600x400',
            'https://placehold.co/600x400',
        ],
        videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
        views: 340,
        ownerId: 'dummyOwner2',
        brokerStatus: 'With Broker',
        vendorNumber: 'VN-938471',
        lastAvailabilityCheck: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
        status: 'approved',
        submittedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S002',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'spacious-3bhk-kharghar',
        propertyType: 'Rental',
        title: 'Spacious 3BHK House with Garden',
        rent: 35000,
        area: 1800,
        city: 'Navi Mumbai',
        locality: 'Kharghar',
        state: 'Maharashtra',
        completeAddress: 'Villa 7, Green Enclave, Sector 10, Kharghar, Navi Mumbai, Maharashtra 410210',
        partialAddress: 'Sector 10, Kharghar, Navi Mumbai',
        ownerName: 'Vikas Rao',
        contactPhonePrimary: '+917766554433',
        contactEmail: 'vikas.r@example.com',
        description: 'A beautiful 3BHK independent house with a lush garden. Perfect for families, located in a peaceful and green locality.',
        furnishedStatus: 'Semi-Furnished',
        amenities: ['Parking', 'Balcony', 'Garden', 'Power Backup'],
        size: '3 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        views: 210,
        ownerId: 'dummyOwner1',
        brokerStatus: 'Without Broker',
        lastAvailabilityCheck: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
        status: 'rejected',
        submittedAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S001',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
        nocUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'modern-2bhk-nerul',
        propertyType: 'Rental',
        title: 'Modern 2BHK in Nerul',
        rent: 30000,
        area: 1100,
        city: 'Navi Mumbai',
        locality: 'Nerul',
        state: 'Maharashtra',
        completeAddress: 'B-501, Tech Residency, Sector 20, Nerul, Navi Mumbai, Maharashtra 400706',
        partialAddress: 'Sector 20, Nerul, Navi Mumbai',
        ownerName: 'Anil Kumar',
        contactPhonePrimary: '+919988776655',
        contactEmail: 'anil.k@example.com',
        description: 'Bright and airy 2BHK, walking distance to major tech parks. Features a spacious living area and modern kitchen appliances.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Gym', 'Elevator'],
        size: '2 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        views: 95,
        ownerId: 'dummyOwner3',
        brokerStatus: 'With Broker',
        lastAvailabilityCheck: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
        status: 'pending',
        submittedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'affordable-1bhk-panvel',
        propertyType: 'Rental',
        title: 'Affordable 1BHK in Panvel',
        rent: 12000,
        area: 600,
        city: 'Navi Mumbai',
        locality: 'Panvel',
        state: 'Maharashtra',
        completeAddress: 'C-3, Sai Apartments, Sector 5, New Panvel, Panvel, Maharashtra 410206',
        partialAddress: 'New Panvel, Panvel, Navi Mumbai',
        ownerName: 'Sunita Gawde',
        contactPhonePrimary: '+919123456789',
        contactEmail: 'sunita.g@example.com',
        description: 'A compact and affordable 1BHK apartment perfect for individuals or small families. Well-connected to the railway station.',
        furnishedStatus: 'Unfurnished',
        amenities: ['Parking', 'Elevator'],
        size: '1 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        views: 450,
        ownerId: 'dummyOwner4',
        brokerStatus: 'Without Broker',
        lastAvailabilityCheck: new Date().toISOString(),
        status: 'approved',
        submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S001',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'cozy-1bhk-andheri',
        propertyType: 'Rental',
        title: 'Cozy 1BHK near Andheri Station',
        rent: 28000,
        area: 550,
        city: 'Mumbai',
        locality: 'Andheri',
        state: 'Maharashtra',
        completeAddress: '7B, Sunrise Apartments, SV Road, Andheri West, Mumbai, Maharashtra 400058',
        partialAddress: 'Andheri West, Mumbai',
        ownerName: 'Priya Deshmukh',
        contactPhonePrimary: '+919876543211',
        description: 'A well-maintained and cozy 1BHK, perfect for a single professional or a couple. Extremely close to Andheri railway and metro station, offering excellent connectivity.',
        furnishedStatus: 'Semi-Furnished',
        amenities: ['Elevator', 'Security', 'Piped Gas'],
        size: '1 BHK',
        images: ['https://placehold.co/600x400'],
        views: 280,
        ownerId: 'dummyOwner6',
        brokerStatus: 'Without Broker',
        lastAvailabilityCheck: new Date().toISOString(),
        status: 'approved',
        submittedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S002',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'student-pg-airoli',
        propertyType: 'PG',
        title: 'Student PG in Airoli',
        rent: 8500,
        area: 120,
        city: 'Navi Mumbai',
        locality: 'Airoli',
        state: 'Maharashtra',
        completeAddress: 'Plot 55, Near Airoli Station, Sector 3, Airoli, Navi Mumbai, Maharashtra 400708',
        partialAddress: 'Sector 3, Airoli, Navi Mumbai',
        ownerName: 'Deepak Sharma',
        contactPhonePrimary: '+918765432109',
        description: 'Clean and secure PG for students with double and triple sharing rooms. Includes WiFi and housekeeping services.',
        furnishedStatus: 'Furnished',
        amenities: ['WiFi', 'Housekeeping', 'Security'],
        size: 'Double Sharing',
        images: [
            'https://placehold.co/600x400',
        ],
        views: 190,
        ownerId: 'dummyOwner5',
        brokerStatus: 'Without Broker',
        vendorNumber: 'VN-112233',
        beds: [
            { id: 'bed1', status: 'vacant' },
            { id: 'bed2', status: 'vacant' },
            { id: 'bed3', status: 'occupied' },
            { id: 'bed4', status: 'occupied' },
            { id: 'bed5', status: 'vacant' },
            { id: 'bed6', status: 'vacant' },
        ],
        lastAvailabilityCheck: new Date().toISOString(),
        status: 'pending',
        submittedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    }
];

export const dummyRoommates: RoommateProfile[] = [
    {
        id: 'rahul-sharma-belapur',
        propertyType: 'Roommate',
        ownerName: 'Rahul Sharma',
        age: 28,
        rent: 20000,
        city: 'Navi Mumbai',
        locality: 'CBD Belapur',
        state: 'Maharashtra',
        completeAddress: 'Seeking a 2BHK in CBD Belapur, Navi Mumbai, Maharashtra',
        partialAddress: 'CBD Belapur, Navi Mumbai',
        contactPhonePrimary: '+919012345678',
        contactEmail: 'rahul.sharma@example.com',
        description: 'Friendly and organized software engineer looking for a male roommate to find and share an apartment with. Prefer a non-smoker, clean and quiet environment.',
        preferences: ['Non-Smoker', 'Clean', 'Drinker', 'Vegetarian'],
        gender: 'Male',
        images: [
            'https://placehold.co/400x400',
        ],
        views: 75,
        ownerId: 'dummyRoommateOwner1',
        hasProperty: false,
        status: 'approved',
        submittedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S001',
        aadhaarCardUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'ankita-reddy-kharghar',
        propertyType: 'Roommate',
        ownerName: 'Ankita Reddy',
        age: 26,
        rent: 18000,
        city: 'Navi Mumbai',
        locality: 'Kharghar',
        state: 'Maharashtra',
        completeAddress: 'Seeking female roommate in Kharghar, Navi Mumbai, Maharashtra',
        partialAddress: 'Kharghar, Navi Mumbai',
        contactPhonePrimary: '+918012345678',
        contactEmail: 'ankita.r@example.com',
        description: "I have a lovely 2BHK and am looking for a female roommate to share it. I enjoy cooking and quiet evenings. Prefer someone clean and respectful.",
        preferences: ['Non-Smoker', 'Clean', 'Drinker', 'Non-Vegetarian'],
        gender: 'Female',
        images: [
            'https://placehold.co/400x400',
        ],
        views: 180,
        ownerId: 'dummyRoommateOwner2',
        hasProperty: true,
        status: 'approved',
        submittedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S002',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'vikram-singh-vashi',
        propertyType: 'Roommate',
        ownerName: 'Vikram Singh',
        age: 31,
        rent: 25000,
        city: 'Navi Mumbai',
        locality: 'Vashi',
        state: 'Maharashtra',
        completeAddress: 'Looking for a flatmate for my 3BHK in Vashi',
        partialAddress: 'Vashi, Navi Mumbai',
        contactPhonePrimary: '+919876501234',
        description: "Marketing professional with a furnished 3BHK in Vashi. Looking for a flatmate (male/female) to occupy one room. I'm into fitness and exploring new cafes on weekends.",
        preferences: ['Pet-Friendly', 'Clean', 'Drinker'],
        gender: 'Male',
        images: [
            'https://placehold.co/400x400',
        ],
        views: 220,
        ownerId: 'dummyRoommateOwner3',
        hasProperty: true,
        status: 'pending',
        submittedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'priya-nair-nerul',
        propertyType: 'Roommate',
        ownerName: 'Priya Nair',
        age: 24,
        rent: 15000,
        city: 'Navi Mumbai',
        locality: 'Nerul',
        state: 'Maharashtra',
        completeAddress: 'Need a roommate for a 2BHK near Seawoods Grand Central',
        partialAddress: 'Nerul, Navi Mumbai',
        contactPhonePrimary: '+918887776665',
        description: "I'm a graphic designer and looking for a creative and friendly female flatmate. My apartment is close to the station and has a great view. I have a cat, so you must be pet-friendly!",
        preferences: ['Pet-Friendly', 'Non-Smoker', 'Clean'],
        gender: 'Female',
        images: [
            'https://placehold.co/400x400',
        ],
        views: 155,
        ownerId: 'dummyRoommateOwner4',
        hasProperty: true,
        status: 'approved',
        submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        verificationTimestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        verifiedBy: 'S001',
        aadhaarCardUrl: 'https://placehold.co/400x300',
        electricityBillUrl: 'https://placehold.co/400x300',
    },
    {
        id: 'neha-gupta-pune',
        propertyType: 'Roommate',
        ownerName: 'Neha Gupta',
        age: 21,
        rent: 9000,
        city: 'Pune',
        locality: 'Koregaon Park',
        state: 'Maharashtra',
        completeAddress: 'Looking for a female roommate to share a PG in Koregaon Park, Pune',
        partialAddress: 'Koregaon Park, Pune',
        contactPhonePrimary: '+918901234567',
        description: "Art student looking for a fun and friendly female roommate for a shared PG. I'm tidy, love to paint, and explore cafes. Let's find a great place together!",
        preferences: ['Non-Smoker', 'Clean', 'Vegetarian'],
        gender: 'Female',
        images: ['https://placehold.co/400x400'],
        views: 95,
        ownerId: 'dummyRoommateOwner5',
        hasProperty: false,
        status: 'pending',
        submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        aadhaarCardUrl: 'https://placehold.co/400x300',
    }
];
